### ISSUE TITLE
Crash in Golang 2023.1 and Ginkgo plugin(9.2)

### ISSUE THREAD

**Issue by krim** [IdeaGinkgo/Intellij-Ginkgo#83]
**Ginkgo version:** 2.9.2

Sometimes I'm faced with crash like this:
```
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor86.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:248)
	at jdk.proxy1/jdk.proxy1.$Proxy44.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:222)
	at com.intellij.execution.process.ColoredProcessHandler.coloredTextAvailable(ColoredProcessHandler.java:68)
	at com.intellij.execution.process.AnsiEscapeDecoder.processTextChunk(AnsiEscapeDecoder.java:107)
	at com.intellij.execution.process.AnsiEscapeDecoder.escapeText(AnsiEscapeDecoder.java:69)
	at com.intellij.execution.process.ColoredProcessHandler.notifyTextAvailable(ColoredProcessHandler.java:57)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:141)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:220)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:204)
	at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:116)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:72)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:153)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:227)
	at com.intellij.util.io.BaseDataReader.lambda$start$0(BaseDataReader.java:48)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoClassDefFoundError: org/codehaus/plexus/util/StringUtils
	at com.github.idea.ginkgo.GinkgoTestEventsConverterV2.processLine(GinkgoTestEventsConverterV2.java:102)
	at com.goide.execution.testing.frameworks.gotest.GoTestEventsConverterBaseImpl.processServiceMessages(GoTestEventsConverterBaseImpl.java:73)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.processConsistentText(OutputToGeneralTestEventsConverter.java:113)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter$1.onTextAvailable(OutputToGeneralTestEventsConverter.java:70)
	at com.intellij.execution.testframework.sm.runner.OutputEventSplitter.onTextAvailableInternal(OutputEventSplitter.kt:79)
	at com.intellij.execution.testframework.sm.runner.OutputEventSplitter.onTextAvailable(OutputEventSplitter.kt:74)
	at com.intellij.smRunner.OutputEventSplitterBase.flushInternal(OutputEventSplitterBase.kt:159)
	at com.intellij.smRunner.OutputEventSplitterBase.flushInternal$default(OutputEventSplitterBase.kt:145)
	at com.intellij.smRunner.OutputEventSplitterBase.processInternal(OutputEventSplitterBase.kt:93)
	at com.intellij.smRunner.OutputEventSplitterBase.process(OutputEventSplitterBase.kt:74)
	at com.intellij.execution.testframework.sm.runner.OutputEventSplitter.process(OutputEventSplitter.kt:59)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.process(OutputToGeneralTestEventsConverter.java:96)
	at com.github.idea.ginkgo.GinkgoTestEventsConverter.process(GinkgoTestEventsConverter.java:76)
	at com.intellij.execution.testframework.sm.SMTestRunnerConnectionUtil$2.onTextAvailable(SMTestRunnerConnectionUtil.java:217)
	... 27 more
Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.util.StringUtils PluginClassLoader(plugin=PluginDescriptor(name=Ginkgo, id=com.github.intellij.ginkgo, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/Toolbox/apps/Goland/ch-0/231.8109.199/GoLand.app.plugins/Intellij-Ginkgo, version=0.9.2, package=null, isBundled=false), packagePrefix=null, instanceId=111, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 41 more
```

Also it doesn't execute the tests, just output the information about how many tests will be executed:
```
GOROOT=/usr/local/Cellar/go@1.19/1.19.8/libexec #gosetup
WORKING_DIRECTORY=/Users/kr/Sites/project-name/app/builders #gosetup
/Users/kr/go/bin/ginkgo -v --focus=Order
Running Suite: Builders suite - /Users/kr/Sites/project-name/app/builders
=======================================================================================================
Random Seed: 1680713340

Will run 12 of 46 specs
````

NB: The same command from shell executes the tests.

**Comment by TaylorOno** [comment]
The fix for this is pending review in the store or you can download it from the [release  page](https://github.com/IdeaGinkgo/Intellij-Ginkgo/releases)

**Comment by krim** [comment]
thanks a lot, now it works ❤️
